spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://47.98.39.45:9097/gxxc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: 'root'
    password: '123456'


server:
  port: 80

#测试调试 1 进行调试  0 正式  正式环境里不需要配置这个参数
debug_test: 1

#一级金额百分比
one_eevel_money_scale: 0.32

#二级金额百分比
two_eevel_money_scale: 0.16
#订单总金额  用户在分派佣金时，检查支付宝、微信收到的真实金额。如果不对，就要告警。
order_money: 2500

logo_file_url: D:\2003\logo.png

qr_code_file_url: D:\2003\

wechat:
  appId: wxc79cfaa1daf98915
  secret: d7999531006d520814412b3cd0805156
  domain:




