spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gxxc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: 'root'
    password: '123456'


server:
  port: 9006

#测试调试 1 进行调试  0 正式  正式环境里不需要配置这个参数
debug_test: 1

#学费类型的产品金额不能低于该值，如果低于该值，将无法插入。
order_money: 2500

logo_file_url: /opt/gxxc/logo.png

qr_code_file_url: d:/static/

credentialsPath: d://2004/

# 项目中图片访问的地址 这边需要用域名访问
img_url: http://www.520xclm.com:8001/

userAgreementPath: /Users/yangx/Desktop/img/out2/


staticPath: D:/static/common/