spring:
  profiles:
    active: test  #合并 application-test.yml 中的配置参数
  #上传文件设置
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 20
      keepAliveSeconds: 120
      queueCapacity: 50
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
  #数据库连接配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.98.39.45:9097/gxxc_0816?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: 'root'
    password: '123456'
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true

#        url: jdbc:mysql://47.96.101.240:6088/gxxc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#        username: 'root'
#        password: 'THXC-DB**2018'

#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml
  mapperLocations: classpath:mybatis/sql/*.xml,classpath:mybatis/sql/extend/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

server:
  port: 81

#学费类型的产品金额不能低于该值，如果低于该值，将无法插入。
order_money: 2500

# 用户的协议
userAgreementPath: /opt/gxxc/nginx/Agreement/


staticPath: /opt/gxxc/nginx/
#证件照片上传的地址 必须要心/结尾
credentialsPath: /opt/gxxc/nginx/

# 项目中图片访问的地址 这边需要用域名访问
img_url: http://www.520xclm.com:8001/

# 邀请码生成时中间的图像地址
logo_file_url: /opt/gxxc/logo.png
#邀请码生成的目录地址
qr_code_file_url: /opt/gxxc/nginx/

#注册下发短信
appSendSMSRegister: app_sendSMS_register
#重置 下发短信
appSendSMSResetting: app_sendSMS_resetting

#科目一
SUBJECT_MARK_1: 90
#科目二
SUBJECT_MARK_2: 90
#科目三
SUBJECT_MARK_3: 90
#科目四
SUBJECT_MARK_4: 90


wxDomain: http://www.520xclm.com/wx
# 接收到第三方支付成功的消息后，支付回调操作
wxPayBackDomain: http://www.520xclm.com/wx
#分配学员学员链接地址
wxassignXyDomain: http://www.520xclm.com/wx
#分配学员教练链接地址
wxassignJlDomain: http://www.520xclm.com/wx

wxMsgTemplate:
  handle: 0jqcQ-ucdPPfGl3WlyquqhaqOSaj1_8wc7jvZTqXh-I
  exam: QyJLmqWBdoJfvRvvWGuWTpdt6-0r2-nGKJXhNTD4sT4
  pay: RzaPPdugSVZJ_p3v6CexYAqmARPkBalAUX-oHzvA4-o
  payBack: RzaPPdugSVZJ_p3v6CexYAqmARPkBalAUX-oHzvA4-o
  assignXy: JjeCO5HE0TnA1bj9HWCIlkMNjm2mxO-1PgmM10xens0
  assignJl: JjeCO5HE0TnA1bj9HWCIlkMNjm2mxO-1PgmM10xens0

wechat:
  appId: wxb01394ea85904296
  secret: 1357c923084a743e10131df166796303
  #设置微信公众号的token
  token: xclmToken
  #设置微信公众号的EncodingAESKey
  aesKey: FaCUOuOXFk2l80CMkrtALclKwFVaFxa4UOzKpBOFNlk
  domain: http://www.520xclm.com
  tradeType: JSAPI
  pay:
    appId: wxb01394ea85904296
    mchId: 1506987921
    mchKey: rFNTUgr6ptfTEe7pTuoEWViJE2Jh3jwU
    subAppId:
    subMchId:
    keyPath: c://apiclient_cert.p12
    domain: http://www.520xclm.com
    trade_type: JSAPI
    notify_url: http://www.520xclm.com:8080/biz/wxPay/notifyCallback
  apppay:
    appId: wxb8c7c134a416a3d1
    mchId: 1510586751
    mchKey: c5407b90f3f35009c3bddcc93e1979a6
    subAppId:
    subMchId:
    keyPath: c://apiclient_cert.p12
    domain: http://www.520xclm.com
    trade_type: JSAPI
    notify_url: http://www.520xclm.com:8080/biz/wxPay/notifyCallback


#定时任务标识
JOB:
  KEY: 123456789
  TOKEN: 987654321
  HOST: 127.0.0.1,47.96.101.240

# 百度图片识别 文本识别是一个，物体主休识别是别一个
baidu:
  img:
    ocr: #图片文本识别 身份证、驾驶证、银行卡 信息读取
      app_id: sE9HAgpK2XKsrKiuorzCoory
      app_key: sE9HAgpK2XKsrKiuorzCoory
      secret_key: HNyUWG5Od5docsq83l5l6hVgdKv6Etng
    detect: #图片检查 识别图片中物体的主体位置
      app_id: 11437782
      app_key: LWlbEbioIv9aWIve9ZOZ583W
      secret_key: vcoxuovajxrtxj0MhhSRZGWxz3Iy3g9E

# 支付宝支付接口 网关(gateway) 分正式环境：https://openapi.alipay.com/gateway.do  还有一个沙盒环境
# 支付宝公钥(alipay_public_key) 这个是支付宝生成的公钥，不是我们自己生成的公钥。我们生成的公钥是给支付宝做验签的。我们给支付宝验签时，必须要用支付宝给我们的公钥进行
#  应用id(app_id)，应用私钥(private_key)，编码格式(charset)，支付宝公钥(alipay_public_key)，签名类型(sign_type)
# billFileUrl  支付宝账单下载的地址
# app_privaie_key_pkcs8 是应用私钥(rsa_private_key_pkcs8文件中的) 此私钥仅用于获取账单文件接口  app_privaie_key 是应用私钥（rsa_private_key文件中的）此私钥仅用于支付接口
alipay:
  app_id: 2018080860937512
  app_privaie_key: MIIEogIBAAKCAQEAtdlEUGi+/wg9Xqn+vporywhem177DnBMjK9ifPDeNRbgAh3EmN02Q4Cn8KpquCkXTvl1HErCJ64cYDpsGZwP99OroDqOT7Vsv/zYamd5dRzFzqXU67mfCn8u74rJYd8YSHDUmSA5ppchVXk0db1P1n9cHY7pWL+/oyPL6ehx4HsPzLXoM340QYFOcMwr3SM/+Vjk6B8tkwF5RoCU9IARGEJ4+l7XpHddez6cdifLsPQ3/E9ER4ZYkjjPo+HiuAgDKmnif74wk2Cu+Ach+um4KTnUMPRoQu4m8NwvpAKYTrbq1SlGv9FM4Ms2HQe1/auuKNWgCk/sI1aJKeYqeqTCoQIDAQABAoIBACy+KYXTT/M2Fst87jX9fvr0szptUz5JOTyARq5RIYtUdoduxZmLDDftpuSbOajYS2jeDgeJCV50A31VwpVGhdNHXHoPDkbkb76JOsJrdUHwc2cV/F6HjG8rveOodUZEexgP0u9eM3EezE/Yg6TYkJVJPuPy7s0sWL2OKDUEQUim9GmHYNSesWBWMO+xZqeY904W1ocdRtVIB6XixgjZW35hO8wclb7dfzVs2ktkKqgtf/fc4JO41aSTX8EVDUEpLy/AIOATQFD2aoms/3D31V7FVY9E/8eJhlPVZBB9mhGnD/tOuE5tQQ5LYPre/DzwX2M2acrddv9nScTVmDK9wfECgYEA5aEF+6WJAA/YJvdZ9Gi1XmZsjHjRqQhuSPCsW9FUXe0Pg5tb6rZKuZ6iQRqLF4j4lspeoq9riypesGOkc/qbdUw4A6aOj5n1CWRBbn2+CRqk37XM6vTD5SeUODShDaBZ6Rbge3rasy8o1ygKbf8m4p7CaE1Tmx4s9Jul+HMEKKUCgYEAyruG3PLPPpefg13I7Pb7vAbAhJo8CgSBK7NpQI61Ur4GO6oZQ+hcI8qjYOULBmuETbamTw+1LKu8xy4AZmbUXJL4LuRMFpSATzHTLY9QAK59Q0egu8TNJYV2pL0xxyYM1sbs9Snq6HIjrSRlRGAtkTvHJ+fMjEFoPXE5ReKjFU0CgYAy71HNbP2DlwAiPJGmhidc5ilDy3TuIqGb6k7BGyC0qOXdEnQEDyVqIQbqnAGoWciSYhc1zOV0/BP+2ktbMoaTMTHnlWVf8w2IZMWixZ+Gk3No8AGhSGO/i9Tz1rC2vg/ThTCME0c5ocdUWlxd48/zSrXivuxBpyLfqzrYbmLIxQKBgB9OJd0ogWgg8bjPWp985BJ82G2hg3Pojim5Yp9dahKE1WGROqWJ0/CS8fecZr9vCtcVRUkgG9HyEwyOxfEKH/DLoRdcmYNDGy0ffISkhK4WQ7GH9gIIucT5fwChVnZyIblorl6NQoDyXx/1Zs3QLDkpCe/Xk3Z1Ayu5uCZagORhAoGASZv+dMmpeIGOU5Srgv3i8UGVoomx/qfFAFl0HWzIaIDfSPHYkeKeBS6EkQWK/ZK/dn0AtUwOveKRYJqbXbrgJJHePKfhWZgD8RbMe/rFGO8KA1F6rI7uqB++mL/gvhHsEuqHQnAy0hbejWwaYIzcF4M8PBC6FV5AxWbAiKwmVK8=
  charset: UTF-8
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyFmtcAdIhy82E5n61hN/tHl3Pr+47rCtNaOH5XuGqP/rX8Ti4VbcY7y0zjcVNr9kL1iNHzxFb3FWh9Megqb00K9chDpzA42fH/wtuJfSrwMdClWWvF+gsn0/Ro5xyHsb0Q5MVhCMaN5Jp1zz38lw3wpo+ocgHlUVqvScG6wohwpr7fZY4oEs1vHOiMe5DUdvtTFJOSM4pt4ffPn+yHsnlmC4zhZQzGDRnLLNvhADNsXNzYEY5PGK2Hmi/+z3B1o/sv9Kf4jlK1U8XxhZXfwApgTywJH4d2VP+zjc2S5v3umsjx4ihlASCcXFPwyQF17WcpF2xIYUBe4VDJqbD0dTsQIDAQAB
  gateway: https://openapi.alipay.com/gateway.do
  sign_type: RSA2
  notify_url: http://www.520xclm.com:8080/biz/alipay/orderFulfil
  bill_file_path: D:\2003
  app_privaie_key_pkcs8: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC12URQaL7/CD1eqf6+mivLCF6bXvsOcEyMr2J88N41FuACHcSY3TZDgKfwqmq4KRdO+XUcSsInrhxgOmwZnA/306ugOo5PtWy//NhqZ3l1HMXOpdTruZ8Kfy7vislh3xhIcNSZIDmmlyFVeTR1vU/Wf1wdjulYv7+jI8vp6HHgew/MtegzfjRBgU5wzCvdIz/5WOToHy2TAXlGgJT0gBEYQnj6Xtekd117Ppx2J8uw9Df8T0RHhliSOM+j4eK4CAMqaeJ/vjCTYK74ByH66bgpOdQw9GhC7ibw3C+kAphOturVKUa/0UzgyzYdB7X9q64o1aAKT+wjVokp5ip6pMKhAgMBAAECggEALL4phdNP8zYWy3zuNf1++vSzOm1TPkk5PIBGrlEhi1R2h27FmYsMN+2m5Js5qNhLaN4OB4kJXnQDfVXClUaF00dceg8ORuRvvok6wmt1QfBzZxX8XoeMbyu946h1RkR7GA/S714zcR7MT9iDpNiQlUk+4/LuzSxYvY4oNQRBSKb0aYdg1J6xYFYw77Fmp5j3ThbWhx1G1UgHpeLGCNlbfmE7zByVvt1/NWzaS2QqqC1/99zgk7jVpJNfwRUNQSkvL8Ag4BNAUPZqiaz/cPfVXsVVj0T/x4mGU9VkEH2aEacP+064Tm1BDktg+t78PPBfYzZpyt12/2dJxNWYMr3B8QKBgQDloQX7pYkAD9gm91n0aLVeZmyMeNGpCG5I8Kxb0VRd7Q+Dm1vqtkq5nqJBGosXiPiWyl6ir2uLKl6wY6Rz+pt1TDgDpo6PmfUJZEFufb4JGqTftczq9MPlJ5Q4NKENoFnpFuB7etqzLyjXKApt/ybinsJoTVObHiz0m6X4cwQopQKBgQDKu4bc8s8+l5+DXcjs9vu8BsCEmjwKBIErs2lAjrVSvgY7qhlD6FwjyqNg5QsGa4RNtqZPD7Usq7zHLgBmZtRckvgu5EwWlIBPMdMtj1AArn1DR6C7xM0lhXakvTHHJgzWxuz1KerociOtJGVEYC2RO8cn58yMQWg9cTlF4qMVTQKBgDLvUc1s/YOXACI8kaaGJ1zmKUPLdO4ioZvqTsEbILSo5d0SdAQPJWohBuqcAahZyJJiFzXM5XT8E/7aS1syhpMxMeeVZV/zDYhkxaLFn4aTc2jwAaFIY7+L1PPWsLa+D9OFMIwTRzmhx1RaXF3jz/NKteK+7EGnIt+rOthuYsjFAoGAH04l3SiBaCDxuM9an3zkEnzYbaGDc+iOKblin11qEoTVYZE6pYnT8JLx95xmv28K1xVFSSAb0fITDI7F8Qof8MuhF1yZg0MbLR98hKSErhZDsYf2Agi5xPl/AKFWdnIhuWiuXo1CgPJfH/VmzdAsOSkJ79eTdnUDK7m4JlqA5GECgYBJm/50yal4gY5TlKuC/eLxQZWiibH+p8UAWXQdbMhogN9I8diR4p4FLoSRBYr9kr92fQC1TA694pFgmptduuAkkd48p+FZmAPxFsx7+sUY7woDUXqsju6oH76Yv+C+EewS6odCcDLSFt6NbBpgjNwXgzw8ELoVXkDFZsCIrCZUrw==


# 客服电话
custom_service_tel: 4000170520

# 微信企业付款，是否强制实名
# NO_CHECK：不校验真实姓名 
# FORCE_CHECK：强校验真实姓名（未实名认证的用户会校验失败，无法转账） 
# OPTION_CHECK：针对已实名认证的用户才校验真实姓名（未实名认证用户不校验，可以转账成功） 该状态在官网上已经被移除，可能后期不会被使用
wx_checkname: FORCE_CHECK
# 微信企业付款时，需要加的IP地址。官方文档 建议传用户端或者服务端的IP。
spbill_create_ip: 47.96.101.240

