spring:
  profiles:
    active: test  #合并 application-test.yml 中的配置参数
  #上传文件设置
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 20
      keepAliveSeconds: 120
      queueCapacity: 50
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000
  #数据库连接配置信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true
#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml
  mapperLocations: classpath:mybatis/sql/*.xml,classpath:mybatis/sql/extend/*.xml

logging:
  config: classpath:log4j2.xml

mapper:
  identity: MYSQL

server:
  port: 81

img_url: http://127.0.0.1:80


#一级金额百分比
one_eevel_money_scale: 0.32

#二级金额百分比
two_eevel_money_scale: 0.16
#订单总金额  用户在分派佣金时，检查支付宝、微信收到的真实金额。如果不对，就要告警。
order_money: 2500

logo_file_url: D:\2003\logo.png

qr_code_file_url: D:\2003\


