spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://47.96.101.240:6088/gxxc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: 'root'
    password: 'THXC-DB**2018'


server:
  port: 9086

#测试调试 1 进行调试  0 正式  正式环境里不需要配置这个参数
debug_test: 0

#学费类型的产品金额不能低于该值，如果低于该值，将无法插入。
order_money: 2500

logo_file_url: /opt/gxxc/logo.png

qr_code_file_url: /opt/gxxc/nginx/
credentialsPath:
wxDomain: http://xclm.xxpt123.com/wx
wxMsgTemplate:
  handle: 0jqcQ-ucdPPfGl3WlyquqhaqOSaj1_8wc7jvZTqXh-I
  exam: QyJLmqWBdoJfvRvvWGuWTpdt6-0r2-nGKJXhNTD4sT4
  pay: RzaPPdugSVZJ_p3v6CexYAqmARPkBalAUX-oHzvA4-o

wechat:
  appId: wxb01394ea85904296
  secret: 1357c923084a743e10131df166796303
  #设置微信公众号的token
  token: xclmToken
  #设置微信公众号的EncodingAESKey
  aesKey: FaCUOuOXFk2l80CMkrtALclKwFVaFxa4UOzKpBOFNlk
  domain: http://xclm.xxpt123.com
  tradeType: JSAPI
  pay:
    appId: wxb01394ea85904296
    mchId: 1506987921
    mchKey: rFNTUgr6ptfTEe7pTuoEWViJE2Jh3jwU
    subAppId:
    subMchId:
    keyPath:
    domain: http://xclm.xxpt123.com
    trade_type: JSAPI
    notify_url: http://xclm.xxpt123.com:8080/biz/wxPay/notifyCallback

